# Generated by Django 4.2.6 on 2023-10-25 05:55

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=221)),
                ('content', models.TextField()),
                ('author', models.CharField(blank=True, max_length=221, null=True)),
                ('image', models.ImageField(upload_to=main.models.image_path)),
                ('file', models.FileField(upload_to=main.models.file_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_free', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
