# Generated by Django 4.2.6 on 2023-10-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
