# Generated by Django 4.2.6 on 2023-10-24 06:35

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(default=1, upload_to=main.models.image_path),
            preserve_default=False,
        ),
    ]
