# Generated by Django 4.2.6 on 2023-10-24 06:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.image_path),
        ),
    ]
